### ISSUE TITLE
Login Page

### ISSUE THREAD

**Issue by atakanguney** [atakanguney/Semantic-Trustworthy-News#7]
- We need to create a login page and a login functionality in frontend and backend.

**Comment by mericturan** [comment]
As in Issue #5, it is better to do it all together.

**Comment by atakanguney** [comment]
I think the better way is that one of us should do the task and make PR to the code. The PR must not be merged to code base, unless it is reviewed and approved. Otherwise, it is hard to gather together and do the job

**Comment by atakanguney** [comment]
@mericturan @esraonal From now on, nobody can merge to master, unless PR got 2 code reviews 👯‍♂ 🚀

**Comment by mericturan** [comment]
I agree with you Atakan. However, for the first few implementations, I think it is better if we do it together. I can't speak on behalf of Esra, but I am not familiar with most of the technology we are going to use to develop Semantic Trustworthy News platform. That is why I would prefer to do it together.

If Esra is confident about herself, then maybe we can do it together Atakan. Besides, it will be easier to arrange time for two of us.

**Comment by esraonal** [comment]
Hi everyone, I also think that at the beginning it is better we work on this together so that we establish or explore which tools we are going to use and how we are going to use them.  I cannot say that I am really confident about how exactly this platform will be built.  We know what we need at least to some extend (well, it is easy to think in terms of concepts) but I am not sure how we bring those pieces together to create such a system in practice. Therefore, I also suggest that we come together again to discuss the practical issues.

**Comment by mericturan** [comment]
It is done.
